package hr.member;

import java.io.Serializable;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2010.05.29 at 01:53:14 오후 KST 
//

/**
* <p>Java class for anonymous complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType>
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="pw" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="jumin" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="admin" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
*       &lt;/sequence>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
 "id",
 "pw",
 "name",
 "jumin",
 "email",
 "admin"
})
@XmlRootElement(name = "user")
public class User implements IMember, Serializable{

 @XmlElement(required = true)
 protected String id;
 @XmlElement(required = true)
 protected String pw;
 @XmlElement(required = true)
 protected String name;
 @XmlElement(required = true)
 protected String jumin;
 @XmlElement(required = true)
 protected String email;
 protected boolean admin;

 /**
  * Gets the value of the id property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getId() {
     return id;
 }

 /**
  * Sets the value of the id property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setId(String value) {
     this.id = value;
 }

 /**
  * Gets the value of the pw property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getPw() {
     return pw;
 }

 /**
  * Sets the value of the pw property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setPw(String value) {
     this.pw = value;
 }

 /**
  * Gets the value of the name property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getName() {
     return name;
 }

 /**
  * Sets the value of the name property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setName(String value) {
     this.name = value;
 }

 /**
  * Gets the value of the jumin property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getJumin() {
     return jumin;
 }

 /**
  * Sets the value of the jumin property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setJumin(String value) {
     this.jumin = value;
 }

 /**
  * Gets the value of the email property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getEmail() {
     return email;
 }

 /**
  * Sets the value of the email property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setEmail(String value) {
     this.email = value;
 }

 /**
  * Gets the value of the admin property.
  * 
  */
 public boolean isAdmin() {
     return admin;
 }

 /**
  * Sets the value of the admin property.
  * 
  */
 public void setAdmin(boolean value) {
     this.admin = value;
 }
	@Override
	public String[] getColumnName() {
		String[] str = {"아이디", "비밀번호", "이름", "주민번호", "이메일", "관리자 여부"};
		return str;
	}
	@Override
	public void setData(String... str) {
		id = str[0];
		pw = str[1];
		name = str[2];
		jumin = str[3];
		email = str[4];
		if(str[5].equals("예") || str[5].equals("true")){
			admin = true;
		}
		else{
			admin = false;
		}
	}
	@Override
	public Object[] toArray() {
		Object[] obj = new Object[6];
		obj[0] = id;
		obj[1] = pw;
		obj[2] = name;
		obj[3] = jumin;
		obj[4] = email;
		obj[5] = new Boolean(admin);
		return obj;
	}
	@Override
	public String[] toStrings() {
		String[] str = new String[6];
		str[0] = id;
		str[1] = pw;
		str[2] = name;
		str[3] = jumin;
		str[4] = email;
		if(admin)
			str[5] = "예";
		else
			str[5] = "아니오";
		return str;
	}
	
	public IMember clone(){
		try {
			return (IMember)super.clone();
		} catch (CloneNotSupportedException e) {
			return null;
		}
	}
	public String[] getFieldName(){
    	String[] str = {"id", "pw", "name", "jumin", "email", "admin"};
    	return str;
    }
	@Override
	public ClassType getClassType() {
		return ClassType.USER;
	}
}
